// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCosOR3joNUOJvpggfqIsD74skGIytsv4Y',
    appId: '1:9803217882:web:26400946f2ac563f97dee3',
    messagingSenderId: '9803217882',
    projectId: 'botnoiseeforyou',
    authDomain: 'botnoiseeforyou.firebaseapp.com',
    storageBucket: 'botnoiseeforyou.firebasestorage.app',
    measurementId: 'G-RJEQR2DLPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA89lgmqdQG7GR2Nvra5BToNled7z6Duns',
    appId: '1:9803217882:android:e7eaef7252fd394397dee3',
    messagingSenderId: '9803217882',
    projectId: 'botnoiseeforyou',
    storageBucket: 'botnoiseeforyou.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAmKssrFoisVIaLnSWmRtFsHTp1sIQ3oE',
    appId: '1:9803217882:ios:62cb4c489580e86497dee3',
    messagingSenderId: '9803217882',
    projectId: 'botnoiseeforyou',
    storageBucket: 'botnoiseeforyou.firebasestorage.app',
    iosBundleId: 'com.example.seeforyouApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAmKssrFoisVIaLnSWmRtFsHTp1sIQ3oE',
    appId: '1:9803217882:ios:62cb4c489580e86497dee3',
    messagingSenderId: '9803217882',
    projectId: 'botnoiseeforyou',
    storageBucket: 'botnoiseeforyou.firebasestorage.app',
    iosBundleId: 'com.example.seeforyouApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCosOR3joNUOJvpggfqIsD74skGIytsv4Y',
    appId: '1:9803217882:web:78c142b07aaff20e97dee3',
    messagingSenderId: '9803217882',
    projectId: 'botnoiseeforyou',
    authDomain: 'botnoiseeforyou.firebaseapp.com',
    storageBucket: 'botnoiseeforyou.firebasestorage.app',
    measurementId: 'G-6VZG5WBX6L',
  );
}
